### ISSUE TITLE
Revamp button strategy

### ISSUE THREAD

**Issue by Jeremy-Walton** [RoleModel/rolemodel-design-system#10]
Update buttons to follow different standard. primary is main, secondary is outline, tertiary is ???? instead of having primary/secondary/tertiary be the color and then having outline and other variations for all those.

This is worth a discussion with @scriswell and @zoopmaster

**Comment by scriswell** [comment]
This is my recommendation that I just sent to Jeremy for future enhancements and how I would like to see this moved forward.
I prefer a semantic approach but a mix of what we have discussed here. One that allows both a semantic name and the ability to modify.
My recommendation going forward is to name the buttons types in the following way
Default (secondary button interactions and general button styles)
Primary (main actionable buttons, should be one per screen/modal in normal circumstances)
Neutral (this would be in place of tertiary and not needed on all projects)
Success
Warning
With the following modifiers available for each as needed
Size
small
medium
large
Style variants
outline
pill
circle
text
This maps well with common UI libraries including Shoelace
The Shoelace documentation accurately describes how I would move forward: https://shoelace.style/components/button
