### ISSUE TITLE
Consider Renaming the semantic color scales to make adding steps easier

### ISSUE THREAD

**Issue by Jeremy-Walton** [RoleModel/rolemodel-design-system#15]

**Comment by scriswell** [comment]
@Jeremy-Walton Here's an example scale:

Color scale where **plus** adds luminosity (Lighter), and **minus** removes luminosity (Darker)
`  --rm-color-#{$color}-plus-3
    --rm-color-#{$color}-plus-2
    --rm-color-#{$color}-plus-1
    --rm-color-#{$color}-base
    --rm-color-#{$color}-minus-1
    --rm-color-#{$color}-minus-2
    --rm-color-#{$color}-minus-3`

Inverted On Label Color scale
`  --rm-color-#{$color}-on-plus-3
    --rm-color-#{$color}-on-plus-2
    --rm-color-#{$color}-on-plus-1
    --rm-color-#{$color}-on-base
    --rm-color-#{$color}-on-minus-1
    --rm-color-#{$color}-on-minus-2
    --rm-color-#{$color}-on-minus-3`

**Comment by scriswell** [comment]
The concept is borrowed from photography and cinematography where you adjust your light exposure with stops of light plus or minus.
