### ISSUE TITLE
Revamp Form styles

### ISSUE THREAD

**Issue by Jeremy-Walton** [RoleModel/rolemodel-design-system#7]
Our form styles having magic numbers all over and need to be cleaned up.

**Comment by scriswell** [comment]
@Jeremy-Walton Since buttons have been revamped let's share a common height for the inputs and buttons to match one another in scale. Perhaps something more generic like `--rm-input-height-small`, etc... If we do this we should also move the tokens into the `base_tokens.scss` file.
