### ISSUE TITLE
Button Group

### ISSUE THREAD

**Issue by Jeremy-Walton** [RoleModel/rolemodel-design-system#76]
Buttons are great, but what if you want multiple next to each other, say for a "tab selection" or option selector? This should serve as a way to group them and change the style slightly.

https://m3.material.io/components/segmented-buttons/guidelines

There might be multiple use cases here.

Things to answer:
- How does this group affect the buttons inside?
- How to achieve a pill look? class on the group or class on each button?
  - On group would be simpler, but on buttons would allow for sides with different radii (do we even want that?)
- How does it handle all the styles of buttons? What if you mix them?
  - Primary, secondary, delete, disabled, pill, icon, etc.

See 
<img width="258" alt="Screen Shot 2022-08-29 at 8 54 53 PM" src="https://user-images.githubusercontent.com/5957102/187324356-8666f0e7-6af9-40c0-a242-cf75b019b363.png">
<img width="248" alt="Screen Shot 2022-08-29 at 9 03 55 PM" src="https://user-images.githubusercontent.com/5957102/187325195-0c3a5c0e-dda7-4bac-ad0c-ecc1a9d2b288.png">

https://shoelace.style/components/button-group

**Comment by scriswell** [comment]
I'd love to see this with a single wrapper element say `.button-group` that will have our button classes as children. Ideally, the parent container would tell the child buttons how to behave with their respective button radius and border details. Something similar to this from Shoelace: https://shoelace.style/components/button-group

`.btn-group
   .btn
        | Left
    .btn
        | Center
    .btn
        | Right`

----

 `.btn-group
   .btn-primary
        | Left
    .btn-primary
        | Center
    .btn-primary
        | Right`
